mappings:
  - canonical: psnd_ex_gdp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)public sector net debt|psnd"
    series_match: "(?i)% of gdp"

  - canonical: psnb_ex_gdp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)public sector net borrowing|psnb"
    series_match: "(?i)% of gdp"

  - canonical: debt_interest_bn_gbp
    source_file: Debt_interest_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)debt interest"
    series_match: "(?i)(£|bn|billion)"

  - canonical: primary_balance_gdp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)primary"
    series_match: "(?i)% of gdp"

  - canonical: gdp_nominal_bn_gbp
    source_file: Economy_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)gdp"
    series_match: "(?i)nominal|current prices"

  - canonical: gdp_deflator_index
    source_file: Economy_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "(?i)gdp deflator"
    series_match: "(?i)index"

  - canonical: cpi_index
    source_file: Executive_summary_charts_and_tables_March_2025.xlsx
    sheet_match: "(?i)cpi|cpih|prices"
    series_match: "(?i)index"
