mappings:
  # --- Public sector net debt (levels) ---
  - canonical: psnd_ex_bn_gbp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^6\\.13$"
    series_match: "^Public sector net debt ex BoE \\(a-c=d\\)$"

  # Optional: total PSND if you want it too
  - canonical: psnd_total_bn_gbp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^6\\.13$"
    series_match: "^Public sector net debt\\s*\\(PSND\\)\\(d\\+g\\)$"

  # --- Public sector net borrowing (levels) ---
  - canonical: psnb_bn_gbp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^6\\.3$|^6\\.4$|^6\\.5$"
    series_match: "^Net borrowing$"

  # --- Debt interest (levels) ---
  - canonical: debt_interest_bn_gbp
    source_file: Aggregates_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^6\\.17$"
    series_match: "^Debt interest \\(net of APF\\)$|^Debt interest$"

  # --- GDP (nominal, bn) ---
  - canonical: gdp_nominal_bn_gbp
    source_file: Expenditure_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^4\\.3$"
    series_match: "^Nominal GDP \\(£ billion\\)$"

  # --- GDP deflator (index) ---
  - canonical: gdp_deflator_index
    source_file: Expenditure_Detailed_forecast_tables_March_2025.xlsx
    sheet_match: "^4\\.3$"
    series_match: "^GDP deflator$"
